from pprint import pprint

core1 = {'hostname': 'Core1',
         'interfaces': {'gig0/0': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                   'encapsulation': 'dot1q',
                                   'mode': 'trunk',
                                   'state': 'no shutdown'},
                        'gig0/1': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                   'encapsulation': 'dot1q',
                                   'mode': 'trunk',
                                   'state': 'no shutdown'},
                        'gig0/2': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                   'encapsulation': 'dot1q',
                                   'mode': 'trunk',
                                   'state': 'no shutdown'}},
         'layer': 'core',
         'mgmt_intf': 'vlan 10',
         'mgmt_ip': '10.10.0.1',
         'mgmt_subnet': '255.255.255.0',
         'platform': 'vIOS'}

core2 = {'hostname': 'Core2',
         'interfaces': {'gig0/0': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                   'encapsulation': 'dot1q',
                                   'mode': 'trunk',
                                   'state': 'no shutdown'},
                        'gig0/1': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                   'encapsulation': 'dot1q',
                                   'mode': 'trunk',
                                   'state': 'no shutdown'},
                        'gig0/3': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                   'encapsulation': 'dot1q',
                                   'mode': 'trunk',
                                   'state': 'no shutdown'}},
         'layer': 'core',
         'mgmt_intf': 'vlan 10',
         'mgmt_ip': '10.10.0.2',
         'mgmt_subnet': '255.255.255.0',
         'platform': 'vIOS'}

distro1 = {'hostname': 'Distro1',
           'interfaces': {'gig0/0': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig0/1': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig0/2': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig0/3': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig1/0': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig1/1': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig1/2': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig1/3': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'}},
           'layer': 'distro',
           'mgmt_intf': 'vlan 10',
           'mgmt_ip': '10.10.0.3',
           'mgmt_subnet': '255.255.255.0',
           'platform': 'vIOS'}

distro2 = {'hostname': 'Distro2',
           'interfaces': {'gig0/0': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig0/1': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig0/2': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig0/3': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig1/0': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig1/1': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig1/2': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig1/3': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'}},
           'layer': 'distro',
           'mgmt_intf': 'vlan 10',
           'mgmt_ip': '10.10.0.4',
           'mgmt_subnet': '255.255.255.0',
           'platform': 'vIOS'}

access1 = {'hostname': 'Access1',
           'interfaces': {'gig0/0': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig0/1': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig0/3': {'mode': 'access',
                                     'state': 'no shutdown',
                                     'vlan': 30}},
           'layer': 'access',
           'mgmt_intf': 'vlan 10',
           'mgmt_ip': '10.10.0.5',
           'mgmt_subnet': '255.255.255.0',
           'platform': 'vIOS'}

access2 = {'hostname': 'Access2',
           'interfaces': {'gig0/0': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig0/1': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig0/3': {'mode': 'access',
                                     'state': 'no shutdown',
                                     'vlan': 30}},
           'layer': 'access',
           'mgmt_intf': 'vlan 10',
           'mgmt_ip': '10.10.0.6',
           'mgmt_subnet': '255.255.255.0',
           'platform': 'vIOS'}

access3 = {'hostname': 'Access3',
           'interfaces': {'gig0/0': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig0/1': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                     'encapsulation': 'dot1q',
                                     'mode': 'trunk',
                                     'state': 'no shutdown'},
                          'gig0/3': {'mode': 'access',
                                     'state': 'no shutdown',
                                     'vlan': 30}},
           'layer': 'access',
           'mgmt_intf': 'vlan 10',
           'mgmt_ip': '10.10.0.7',
           'mgmt_subnet': '255.255.255.0',
           'platform': 'vIOS'}

access4 = {'hostname': 'Access4',
                             'interfaces': {'gig0/0': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                                       'encapsulation': 'dot1q',
                                                       'mode': 'trunk',
                                                       'state': 'no shutdown'},
                                            'gig0/1': {'allowed_vlans': '1,10,20,30,40,50,60,70',
                                                       'encapsulation': 'dot1q',
                                                       'mode': 'trunk',
                                                       'state': 'no shutdown'},
                                            'gig0/3': {'mode': 'access',
                                                       'state': 'no shutdown',
                                                       'vlan': 30}},
                             'layer': 'access',
                             'mgmt_intf': 'vlan 10',
                             'mgmt_ip': '10.10.0.8',
                             'mgmt_subnet': '255.255.255.0',
                             'platform': 'vIOS'}

all_devices = [core1, core2, distro1, distro2, access1, access2, access3, access4]

core = [core1, core2]

distro = [distro1, distro2]

access = [access1, access2, access3, access4]

for device in all_devices:
    pprint(device)
